### ISSUE TITLE
[BUG] Timestamps are wrong (timezone/hours offset)

### ISSUE THREAD

**Issue by jwmza** [deref/exo#166]
**Describe the bug**
In my actual local time, it is 12:38. The logs from `tick` correctly show this time, but the timestamps we create on the far left shows 4:38, an incorrect time.

**Expected behavior**
Our timestamps === actual user local time.

**Screenshots**
![image](https://user-images.githubusercontent.com/51100181/129234854-c28da10b-12e5-42b0-838a-ad89520809fd.png)

**System Info:**
 - OS: Windows (WSL Ubuntu)
 - Component: GUI
 - Version: Dev (>2021.07.30)

**Comment by BenElgar** [comment]
For me they show up as GMT and I thought that was intentional

**Comment by BenElgar** [comment]
Though I agree that a "Z" suffix to indicate Zulu time would be helpful

**Comment by jwmza** [comment]
I'd rather they use _my_ timezone, not GMT.

However, it's probably best if this is an easily configurable switch, like color theme or any other user preference.

**Comment by brandonbloom** [comment]
My preference is to show local time and then have a hover/tooltip/etc with UTC. That gives you the best of both worlds: Local time for sanity while working independently, and a common timestamp for communicating when collaborating with others (which is less relevant for us now).

A cursory inspection suggests that the GUI already does the correct thing: loads UTC & converts to local during display. But the timestamps coming from the server seem wrong, so there might be a translation issue somewhere in the logging internals.

Also, the `exo logs` CLI command does not do a local time translation I don't think, so that needs to be fixed too.

**Comment by brandonbloom** [comment]
OK, fixed this. @jwmza do you have a list of small UX enhancements somewhere? If so, 1) point me to it and 2) add the hover/UTC thing to it. If not, can we create one? :)

**Comment by brandonbloom** [comment]
Oh, hm, looks like i fixed this for `exo logs` in CLI, but not yet for the GUI.

**Comment by jwmza** [comment]
> OK, fixed this. @jwmza do you have a list of small UX enhancements somewhere? If so, 1) point me to it and 2) add the hover/UTC thing to it. If not, can we create one? :)

No I don't have a list - I'll make one tomorrow.
