### ISSUE TITLE
[BUG] Cannot recover from bad spec

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#270]
**This is only an issue on the interpolation branch.**

If a user applies a docker compose spec that is invalid in such a way that it cannot be unmarshalled this cannot be recovered from. This is because the spec is saved in the state file before it is validated and every future attempt to manipulate the spec attempts to unmarshal this bad spec, which fails.

To recreate, apply a spec like this:
```docker-compose.yaml
services:
  t0:
    image: bash
    command: sleep infinity
    ports:
      - "443:" # This is an invalid port specification
```

Running this with `dexo run` will appropriately fail with an `invalid port mapping syntax` error. The problem is that even if the invalid specification is fixed, future commands will fail until the spec is manually removed from the state file:
```
deleting frontend unmarshalling spec: invalid port mapping syntax
```

The solution is presumably to validate the spec before writing.

**Comment by brandonbloom** [comment]
Yikes. Good catch.

Somewhat related, I've opened #271

> This is because the spec is saved in the state file before it is validated and every future attempt to manipulate the spec attempts to unmarshal this bad spec, which fails.

Subtle correction: I think it is failing on _all_ attempts to invoke controller methods, not just future/subsequent attempts after the first one.

> The solution is presumably to validate the spec before writing.

This might be part of the solution, but I don't think it is a complete solution. In theory, even if the spec is value now, it can become invalid later. For example, if the environment variables change. Rather than try to avoid writing bad components, I'd rather be more robust to errors in bad components. For example, if a component fails to initialize, then we should ignore the invalid spec on a component update, skipping any dispose step, and treating it like a fresh initialize.

This brings up a related issue, that the procfile stuff already suffers from: Variable interpolation means that if we don't store the variable state, we actually can't accurately reproduce the previous spec on an update. Ideally, we'd automatically capture the variable bindings that were used during interpolation, so that subsequent updates can correctly diff.

**Comment by brandonbloom** [comment]
> This is only an issue on the interpolation branch.

Is that actually true? or does that branch only make it worse?

I'd really like to land #266, but this seems like the blocker to fix first.

**Comment by BenElgar** [comment]
Yes, I believe so. On master the given example fails at `loadManifest` but on the interpolation branch `loadManifest` succeeds and, as a result, the bad spec is written to the state file, rendering it broken.

https://github.com/deref/exo/blob/98527c58795bfe2cb96515d190715982b804564d/internal/core/server/workspace.go#L105

**Comment by brandonbloom** [comment]
Another thought on this topic: We should probably make it so that destroy operations can operate on state alone without any spec, this way it would be much less likely to wind up in this situation.

**Comment by brandonbloom** [comment]
Hey @BenElgar I think #387, #321, and #280 combined should be enough to resolve this. What do you think?

**Comment by BenElgar** [comment]
I think it depends on the answer to https://github.com/deref/exo/pull/387#pullrequestreview-768817302. Perhaps that PR changes something fundamental but I'm not sure I see what.

**Comment by brandonbloom** [comment]
I answered over there. Let me know if that clears it up.

**Comment by BenElgar** [comment]
Okay, that makes sense. I'm still not entirely sure that we perform sufficient validation before transforming the spec into the state that I'd be confident that people won't ever run into problems — but I'm happy to move on and see if that happens in practice.

**Comment by brandonbloom** [comment]
I think that's a separate problem & one which is mitigated by #271. Closing this now.
