### ISSUE TITLE
[FEATURE] exo logs should have a non-following mode

### ISSUE THREAD

**Issue by ryfow** [deref/exo#469]
**Is your feature request related to a problem? Please describe.**

I'd like to export the current logs of a service to a file so I can examine them with tools I already know how to use. As I workaround, I can `exo logs | tee logfile.log` and then hit CTRL-C, but that's annoying.

**Describe the solution you'd like**

I'd like to see `exo logs` work like `tail` & `docker logs` where you can optionally add a `-f` to get a following version. If you don't specify `-f`, you just get a current snapshot of the logs.

**Describe alternatives you've considered**

Leaving the default as is but adding an argument for getting a snapshot would also work.

**Comment by brandonbloom** [comment]
Great feedback, thanks. We'll probably stay with following-by-default, since it's the most convenient/common operation from folks we've talked to, but can definitely add flags for controlling output/behavior.

Would `--no-follow` do the trick for you?

Could also - potentially - add a separate `exo tail` command, which takes the more traditional flags & define `exo logs` in terms of `exo tail --follow`.

**Comment by ryfow** [comment]
Yeah, either option would do the trick.
