### ISSUE TITLE
Underscore (or similiar) in component names

### ISSUE THREAD

**Issue by peyloride** [deref/exo#72]
Hello,

My Procfile has some processes named like `sidekiq_invoice_outbound` and exo does not accept that, I don't know why exactly.

**Comment by brandonbloom** [comment]
Hi @peyloride,

The current rules for component names are extremely restrictive and conservative, but we might relax them. Right now, names must be valid as domain names, which do not permit underscores. This is relevant because we're likely to add functionality around domain name management.

One thing we can do immediately, however, is to do some automatic renaming/translation when handling Procfiles. Will investigate.

Thanks,
Brandon

**Comment by brandonbloom** [comment]
@peyloride Addressed this in #73. In the next release, we'll warn about the underscores, but translate them to dashes automatically.
