### ISSUE TITLE
cd/command chaining not supported in Procfile

### ISSUE THREAD

**Issue by kendru** [deref/exo#77]
Foreman now supports `cd` and command chaining within a Procfile, e.g.: 

```
gui: cd gui && npm i && npm run dev
```

Exo does not allow this behviour. The workaround is the following:

```
gui: sh -c 'cd gui && npm i && npm run dev'
```

**Comment by brandonbloom** [comment]
I didn't realize you could do this with Procfiles! I guess it makes sense if they are just passing a string along to a shell.

`cd` is pretty easy for us to support as a special case, we already handle environment variables. However, it's not clear to me what the right behavior is for chains. I'd like to keep the process component type free of variable interpretation, etc for security and simplicity reasons. Maybe we should detect pipelines and automatically inject the `sh` workaround? Some other idea?

**Comment by kendru** [comment]
@brandonbloom I like the idea of just passing it to `sh` if we detect any features that we do not handle natively.

**Comment by brandonbloom** [comment]
For some reason, that scares me a little bit, but I'm not sure why...

**Comment by BenElgar** [comment]
I'm not sure I see the point of not always passing everything to `bash` or `sh`. I can't see any particular security concern given the assumption that any user who has the ability to write to the procfile also has the power to perform arbitrary execution.

**Comment by brandonbloom** [comment]
I'm _mostly_ not worried about security. However, I am concerned about the impact on the component architecture and UX. I _think_ it's OK if we encode the arguments properly to handle escaping/quoting, and then run a process of like `/bin/bash` or whatever with the appropriate args, but I don't think the underlying unix process primitive should be "run a bash script". The reason for this is that we can't necessarily analyze the contents of the bash script to present good UI. We can always fallback to a text editor, but it would be nice to have as structured-as-possible data for good editing experience.

Right now, we support a strict subset of bash syntax _in the GUI_. I went down that road because if you support bash syntax at the component level, you wind up with double quoting in the CLI interface. For instance, imagine the `tick` program accepted a `seconds` argument: `exo new process p1 -- tick 5` to tick every 5 seconds. Now consider `exo new process p2 -- tick $tick_frequency` vs `exo new process p3 -- tick '$tick_frequency'`. Here, p1 is pretty simple and clear. But p2 and p3 are very different. In p2, substitution is performed by your shell. In p3, the substitution would have to be performed by the process component controller. If p3 works, then p2 is now subject to _double_ substitution! Once by you shell, and once by the component controller. Imagine if you did `export tick_frequency='$some_other_variable_in_quotes'`.

Of course, you can always run `exo new process p4 -- sh '-c' 'tick $tick_frequency'` which would explicitly opt-in to delayed substitution. I suspect that this would be OK as a fallback for procfile importing, but it is possible there is a small detail I'm overlooking there. @kendru was this what you suggested?

If we do support substitution in our process specs, I suspect we may want some richer and more easily analyzed language than typical sh syntax. See also #181 and in particular K8s' use of Go templates.

**Comment by brandonbloom** [comment]
cc @finnigantime
